[package]
name = "Mess"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
ndarray = "0.15.6"
phf = "0.11.2"
phf_macros = "0.11.2"
phf_shared = "0.11.2"
rand = "0.8.5"
rand_pcg = "0.3.1"
